name: docker-build

on:
  workflow_call:
    inputs:
      images:
        description: Passed to docker/metadata-action
        type: string
        required: true
      cache-image:
        description: Passed to int128/docker-build-cache-config-action
        type: string
        required: true
      context:
        description: Passed to step-security/docker-build-push-action
        type: string
        required: true
      platforms:
        description: Passed to step-security/docker-build-push-action
        type: string
        required: true
    outputs:
      image-uri:
        description: Image URI
        value: ${{ jobs.build.outputs.image-uri }}

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      image-uri: ghcr.io/${{ github.repository }}/e2e@${{ steps.build.outputs.digest }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: step-security/docker-login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: metadata
        with:
          images: ${{ inputs.images }}
          # avoid overwriting the latest tag because metadata-action does not add a suffix to it
          flavor: latest=false,suffix=-amd64
      - uses: int128/docker-build-cache-config-action@d1b27ffbf29fb93b7239130db030c702198fd52b # v1.64.0
        id: cache
        with:
          image: ${{ inputs.cache-image }}
      - uses: step-security/setup-buildx-action@v4
      - uses: step-security/docker-build-push-action@v7
        id: build
        with:
          push: true
          context: ${{ inputs.context }}
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: ${{ steps.cache.outputs.cache-from }}
          cache-to: ${{ steps.cache.outputs.cache-to }}
          platforms: ${{ inputs.platforms }}
